language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t viliuxaaa/docker-react -f Fockerfile.dev .

script:
  - docker run -e CI=true viliuxaaa/docker-react npm run test
